using System.Text;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using FluentValidation.Results;
using RoEFactura.Extensions;
using RoEFactura.Generation;
using RoEFactura.Validation;
using UblSharp;

namespace RoEFactura.Tests.Generation;

/// <summary>
/// Test helper around generated bytes: the raw text, an <see cref="XDocument"/> with XPath helpers
/// (prefixes <c>inv</c>, <c>cac</c>, <c>cbc</c>) and the local <see cref="RoCiusUblValidator"/> result
/// after loading the XML through <see cref="UblSharpExtensions.LoadInvoiceFromXml"/>.
/// </summary>
internal sealed class GeneratedXml
{
    public const string InvoiceNamespace = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2";
    public const string CacNamespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2";
    public const string CbcNamespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2";

    private readonly XmlNamespaceManager _namespaces = CreateNamespaces();

    private GeneratedXml(byte[] bytes)
    {
        Bytes = bytes;
        Text = Encoding.UTF8.GetString(bytes);
        Document = XDocument.Parse(Text);
    }

    public byte[] Bytes { get; }

    public string Text { get; }

    public XDocument Document { get; }

    public static GeneratedXml From(EInvoiceDocument document)
    {
        return new GeneratedXml(new EInvoiceXmlGenerator().Generate(document));
    }

    public ValidationResult ValidateLocally()
    {
        InvoiceType? invoice = UblSharpExtensions.LoadInvoiceFromXml(Text);
        if (invoice is null)
        {
            throw new InvalidOperationException("The generated XML did not load as a UBL Invoice.");
        }

        return new RoCiusUblValidator().Validate(invoice);
    }

    public IReadOnlyList<XElement> Elements(string xpath)
    {
        return Document.XPathSelectElements(xpath, _namespaces).ToList();
    }

    public XElement? Element(string xpath)
    {
        return Document.XPathSelectElement(xpath, _namespaces);
    }

    public string? Value(string xpath)
    {
        return Element(xpath)?.Value;
    }

    private static XmlNamespaceManager CreateNamespaces()
    {
        XmlNamespaceManager manager = new(new NameTable());
        manager.AddNamespace("inv", InvoiceNamespace);
        manager.AddNamespace("cac", CacNamespace);
        manager.AddNamespace("cbc", CbcNamespace);
        return manager;
    }
}
